### ISSUE TITLE
Unsure of Mark

### ISSUE THREAD

**Issue by JaneyCapers** [hmteditors/2015office3#1]
on our hard copy this is ἐλεύσεσθαι ἄτην. We don't see "αι" but there is a mark after the  Θ that we are unsure of that could be an ending.

> urn:cite:hmt:vaimg.VA254RN-0425@0.2662,0.2703,0.1055,0.0169

**Comment by JaneyCapers** [comment]
Or is this an elision?

**Comment by StephanieML** [comment]
hmmm, my first thought would be to say an elision, but I'm not as familiar with 15th century greek hands. Grab Ineke if you see her walking around.

**Comment by JaneyCapers** [comment]
We found another that is very similar and is an elision. 

> urn:cite:hmt:vaimg.VA254RN-0425@0.3384,0.3239,0.045,0.0188

_We are marking both as elisions._
