### ISSUE TITLE
Unsure of characters

### ISSUE THREAD

**Issue by JaneyCapers** [hmteditors/2015office3#2]
This entire word is different from the hard copy edition. Most of the letters are clear, but these two we are unsure of.

> urn:cite:hmt:vaimg.VA254RN-0425@0.3114,0.3767,0.0203,0.0188

**Comment by JaneyCapers** [comment]
Found it again in a place where it is more clearly ες  ligature.

> urn:cite:hmt:vaimg.VA254RN-0425@0.4781,0.3806,0.0203,0.0188

**Comment by StephanieML** [comment]
i agree
